trigger:
- '*'
resources:
  repositories:
  - repository: test-scripts
    type: git
    name: Testing-Stuff
    ref: main

variables:
- group: Script execution variables

jobs:
- job: ExecuteSQLScript
  displayName: 'Execute SQL Script'
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: git fetch
    displayName: 'Fetch latest changes'  

  - checkout: test-scripts
  - task: PowerShell@2
    displayName: 'Execute PowerShell Script'
    inputs:
      targetType: 'inline'
      script: |
        $server = "$(ServerName)"
        $database = "$(DatabaseName)"
        $username = "$(Username)"
        $password = "$(Password)"
        
        # Set the path to the SQL script
        $scriptPath = 'test-scripts/Test-Script-1.sql'

        Write-Host "Server: $server"
        Write-Host "Database: $database"
        Write-Host "Username: $username"
        Write-Host "Password: $password"
        
        # Read the SQL script content
        $sqlScript = Get-Content -Path $scriptPath -Raw

        Write-Host "SQL script content:"
        Write-Host $sqlScript

        try {
            # Attempt to execute the SQL script
            Invoke-Sqlcmd -ServerInstance $server -Database $database -Username $username -Password $password -Query $sqlScript

            Write-Host "SQL script executed successfully."
        }
        catch {
            Write-Host "Error executing SQL script: $_"
            exit 1 # Fail the pipeline if there's an error
        }
